### ISSUE TITLE
RuntimeError: invalid argument 1: input is not contiguous

### ISSUE THREAD

**Issue by Silenthinker** [LiyuanLucasLiu/LM-LSTM-CRF#12]
When training `LM_LSTM_CRF` model, I encountered the following error:
```sh
Traceback (most recent call last):         
  File "train_wc.py", line 190, in <module>
    loss = crit_ner(scores, tg_v, mask_v)
  File "/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/local/LM-LSTM-CRF/model/crf.py", line 306, in forward
    mask[idx].view(bat_size, 1).expand(bat_size, self.tagset_size)).view(bat_size, -1)
  File "/local/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 510, in view
    return View.apply(self, sizes)
  File "/local/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 96, in forward
    result = i.view(*sizes)
RuntimeError: invalid argument 1: input is not contiguous at /opt/conda/conda-bld/pytorch_1503965122592/work/torch/lib/TH/generic/THTensor.c:231
```
I solved this problem by calling `contiguous()` to make the mentioned input contiguous. Maybe this needs a minor fix.

**Comment by LiyuanLucasLiu** [comment]
Thanks for reporting the bug!
