### ISSUE TITLE
Fix pre-trained embedding fails by requires_grad=False. 

### ISSUE THREAD

**Issue by xiaoleihuang** [LiyuanLucasLiu/LM-LSTM-CRF#34]
Hi, 
I am testing if I could fix the embedding weights by setting requires_grad=False
Here is my code:
`self.word_embeds.weight = nn.Parameter(pre_word_embeddings, requires_grad=False)`

But I got:
`
Traceback (most recent call last):
  File "train_wc.py", line 202, in <module>
    optimizer = optim.SGD(ner_model.parameters(), lr=args.lr, momentum=args.momentum)
  File "/anaconda3/lib/python3.6/site-packages/torch/optim/sgd.py", line 56, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/anaconda3/lib/python3.6/site-packages/torch/optim/optimizer.py", line 61, in __init__
    raise ValueError("optimizing a parameter that doesn't "
ValueError: optimizing a parameter that doesn't require gradients
`
I think because the embedding was initialized as parameters, and all the parameters were optimized as a whole. How could I fix the embedding while not conflict with the optimizer? Thanks!

**Comment by xiaoleihuang** [comment]
I solved by refer to [here](https://github.com/pytorch/pytorch/issues/679)
