### ISSUE TITLE
train_w.py Error

### ISSUE THREAD

**Issue by dungdx34** [LiyuanLucasLiu/LM-LSTM-CRF#43]
hi Liyuan :)
I have a error when I run train-w.py:
On Pytorch 0.3.0
Traceback (most recent call last):
  File "train_w.py", line 193, in <module>
    loss.backward()
  File "/home/dungdx4/anaconda2/envs/python_anaconda_3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/dungdx4/anaconda2/envs/python_anaconda_3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: dimension specified as 0 but tensor has no dimensions

On Pytorch 0.4:
Traceback (most recent call last):          
  File "train_w.py", line 189, in <module>
    fea_v, tg_v, mask_v = packer.repack_vb(feature, tg, mask)
  File "/home/dungdx4/LM-LSTM-CRF-master-0.4/model/crf.py", line 107, in repack_vb
    fea_v = torch.Tensor(feature.transpose(0, 1)).cuda()
TypeError: expected torch.FloatTensor (got torch.LongTensor)

**Comment by LiyuanLucasLiu** [comment]
thanks for asking, i've modified the implementation to make it work with Pytorch0.4

**Comment by xiaoxiaoAurora** [comment]
Hi, Liyuan, I encountered the following problem while running train_w.py, 
Traceback (most recent call last):
  File "/home/liuxiao/workspace/cged/cged_pytorch/train.py", line 117, in <module>
    shrink_to_corpus=args.shrink_embedding)
  File "/home/liuxiao/workspace/cged/cged_pytorch/models/utils.py", line 457, in load_embedding_wlm
    embedding_tensor_1 = torch.FloatTensor(pretrained_weight)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.

And ,at the line 457, my coding as follows:
    if not shrink_to_corpus:
        pretrained_weight = np.asarray(outdoc_embedding_array)
        embedding_tensor_1 = torch.from_numpy(pretrained_weight)
        word_emb_len = embedding_tensor_0.size(1)
        assert(word_emb_len == emb_len)
